version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://root:1591@db:5432/feral
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1591
      POSTGRES_DB: feral
    ports:
      - "5432:5432"
